services:
  kafka:
    container_name: dotnetbus-kafka
    image: apache/kafka:3.8.0
    ports:
      - 9092:9092
#    command: >
#      sh -c "sleep 20 && sh /opt/kafka/bin/kafka-topics.sh --create --topic trade-request --bootstrap-server localhost:9092 &&
#             sh /opt/kafka/bin/kafka-topics.sh --create --topic trade-status  --bootstrap-server localhost:9092"

